In [1]:
#importando a bibloteca
import numpy as np

In [ ]:
quantidade_produtos = [10, 5, 3, 8]
custo_produtos = [5, 10, 2, 3]

array_quantidade = np.array(quantidade_produtos)
array_custo = np.array(custo_produtos)

faturamento = array_quantidade * array_custo

print(f"O faturamento sera de: {faturamento}")
print(type(faturamento))


O faturamento sera de: [50 50  6 24]
<class 'numpy.ndarray'>


In [6]:
#gerara um array automarico
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Criar duas listas:
-5 produtos (apenas inserir valores)
-A primeira lista, custo do produto
-A segunda lista, o preco  de venda
-desafio; Calcular o lucro de cada produto.

In [9]:
CustoP = [5, 4 , 10 , 6 , 3 ]
precoV = [15, 10, 20 ,21 , 7 ]

CustoP_array = np.array(CustoP)
precoV_array = np.array(precoV)

Lucro = precoV_array -CustoP_array
print(f"O lucro sera de: {Lucro}")

O lucro sera de: [10  6 10 15  4]


In [ ]:
custo = []
preco = []

while len(custo) & len(preco) < 5:
    valorC = int(input("Diga o custo dos itens: "))
    custo.append(valorC)
    valorP =  int(input("Diga p preco de venda: "))
    preco.append(valorP)


custo_array = np.array(custo)
preco_array = np.array(preco)
lucro = preco_array - custo_array

print("Os seu lucro será", lucro)


[ 7  8 46  5 -1]


In [ ]:
salarios = np.array([2, 3, 4 , 5 ,6 , 5000])
maior_salario = np.max(salarios)

In [ ]:
menor_salario = np.min(salarios)

In [ ]:
media_salarios = np.mean(salarios)
print(f"{media_salarios:.2f}")

Criar uma lista de vendas por dia 
vendas = [10,20,45,5,90]
-Exibir a Maior venda 
-exibir a menor venda
- exibir a média da vendas
-exibir a mediana de vendas

In [ ]:
vendas = np.array([10,20,45,5,90])

maior = np.max(vendas)
menor = np.min(vendas)
media = np.mean(vendas)
mediana = np.median(vendas)

print("="*64)
print("a lista é:")
print(vendas)
print("="*64)
print(f"o maior é {maior}, o menor é {menor} a media é {media} e a mediana é {mediana}")
print("="*64)


a lista é:
[10 20 45  5 90]
o maior é 90, o menor é 5 a media é 34.0 e a mediana é 20.0


Biblioteca Pandas

In [2]:
vendas = [10, 20,45,5,90] # a biblioteca que faz isso é a numpy ou np
array_vendas = np.array(vendas)


print(np.max(array_vendas))
print(np.min(array_vendas))
print(np.mean(array_vendas))
print(np.median(array_vendas))



90
5
34.0
20.0
